name: CI/CD for project
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test
        env:
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
